server:
    port: 4002
    error:
        include-message: always
        
eureka:
    client:
      serviceUrl:
        default: http://10.0.0.127:8761/eureka

spring:
    application:
        name: organisation_management
    cassandra:
        local-datacenter: datacenter1
        keyspace-name: yowyobdb
        port: 9042
        contact-points: localhost


yowyob:
    openapi:
        prod-url: http://localhost:4002
        dev-url: http://localhost:4002
    
data:
    product-dir: /src/main/resources/image





