server:
    port: 4000
    error:
        include-message: always

spring:
    application:
        name: gestion_organisation
    cassandra:
        local-datacenter: datacenter1
        keyspace-name: gts_organisation
        port: 9042
        contact-points: localhost


yowyob:
    openapi:
        prod-url: http://localhost:4000
        dev-url: http://localhost:4000
    
data:
    product-dir: /src/main/resources/image