server:
    port: 4004
    error:
        include-message: always
eureka:
    client:
     serviceUrl:
        default: http://10.0.0.127:8761/eureka

spring:
    application:
        name: agency_maganement
    cassandra:
        local-datacenter: datacenter1
        keyspace-name: yowyobdb
        port: 9042
        contact-points: localhost


yowyob:
    openapi:
        prod-url: http://localhost:4004
        dev-url: http://localhost:4004
    
data:
    product-dir: /src/main/resources/image